### ISSUE TITLE
Error in write access to outfile

### ISSUE THREAD

**Issue by RobertPatzke** [jayway/AndroidGradleExample#1]
First of all: Thank You very much for publishing such ideas and solutions. 
I tried to use Your extensions of gradle files but an error occurred.  My knowledge is to less to find the reason:
Error:Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.
in this line:
 output.outputFile = new File(output.outputFile.parent, newApkName)
I am using Android Studio 3.0 on Ubuntu.
Robert Patzke

**Comment by erikogenvik** [comment]
Thanks, I've now pushed fixes for Android Studio 3.0.
