### ISSUE TITLE
How to implement auto-increasing version code number?

### ISSUE THREAD

**Issue by fvdcx** [jayway/AndroidGradleExample#2]
Hi @erikogenvik , I saw the blog about auto generated version number. I still had one question, how could we implement auto-increasing version code number?
Say if version is "1.2.0-RC100" in gradle.properties, and we build an apk based on that.
How the version will be "1.2.0-RC101" next time? Is it done manually?

**Comment by erikogenvik** [comment]
Hi, for this you would instead use the https://github.com/researchgate/gradle-release plugin.
